global:
  scrape_interval: 60s
  scrape_timeout: 60s
  evaluation_interval: 60s

# scrape metrics from the prometheus server itself
scrape_configs:
  - job_name: prometheus
    scrape_interval: 60s
    scrape_timeout: 60s
    metrics_path: /metrics
    static_configs:
      - targets:
          - localhost:9090

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]
    bearer_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQiLCJpYXQiOjE3MjE2NzgzOTAsImV4cCI6MTcyMjI4MzE5MH0.4GsTGu0Yc9-irygXLqg6cCh05IES4VVHzgsxCp-y4cE

  # Discover targets from Eureka and scrape metrics from them (Whitebox monitoring)
  - job_name: eureka-service
    scrape_interval: 15s
    scrape_timeout: 15s
    eureka_sd_configs:
      - server: http://eureka-server:8761/eureka/v2
        refresh_interval: 30s
    relabel_configs:
      - source_labels: [__meta_eureka_app_name]
        target_label: application
      - source_labels: [__meta_eureka_app_instance_metadata_metrics_path]
        target_label: __metrics_path__
      - source_labels: [__address__]
        target_label: instance

    # Discover targets from Eureka and probe the health endpoints via the Blackbox Exporter (Blackbox monitoring)
  - job_name: blackbox-via-service-discovery
    params:
      module:
        - http_2xx
    scrape_interval: 15s
    scrape_timeout: 15s
    metrics_path: /probe
    eureka_sd_configs:
      - server: http://eureka-server:8761/eureka/v2
        refresh_interval: 30s
    relabel_configs:
      - source_labels: [__meta_eureka_app_name]
        target_label: application
      - source_labels: [__meta_eureka_app_instance_healthcheck_url]
        target_label: __param_target
      - source_labels: [__address__]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115
