services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend-net

  ### Zipkin
  zipkin:
    image: openzipkin/zipkin:2.24.2
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - backend-net

networks:
  backend-net:
    external: true
